language: node_js
node_js:
  - "0.11"
services:
  - mongodb
before_script: 'npm install -g istanbul && npm install -g mocha'
after_script: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'